
R3F_LOG_CFG_remorqueurs = [
	"Truck",
        "Car",
	"TowingTractor",
	"Tractor",
	"BRDM2_Base",
	"BTR90_Base",
	"GAZ_Vodnik_HMG",
	"LAV25_Base",
	"StrykerBase_EP1",
	"MLRS",
	"Fishing_Boat",
	"RHIB",
	"Smallboat_1",
	"smallboat_2"
];

/**
 * List of class names of towables objects.
 * Liste des noms de classes des objets remorquables.
 */
R3F_LOG_CFG_objets_remorquables = [
	"HMMWV_Base",
	"Truck",
	"Car",
	"GAZ_Vodnik_HMG",
	"BRDM2_Base",
	"BTR40_MG_base_EP1",
	"Ship",
	"Ikarus",
	"Tractor",
	"UAZ_Base",
	"SkodaBase",
	"hilux1_civil_1_open",
	"Pickup_PK_base",
	"Offroad_DSHKM_base",
	"C130J",
	"Lada_base",
	"Mi24_Base",
	"VWGolf",
	"hilux1_civil_3_open_EP1",
	"LandRover_Base",
	"S1203_TK_CIV_EP1",
	"ArmoredSUV_Base_PMC",
	"SUV_Base_EP1",
	"Volha_TK_CIV_Base_EP1",
	"BAF_Jackal2_BASE_D",
	"An2_Base_EP1",
	"M119",
	"F35_base",
	"L39_base",
	"su34",
	"UAV",
	"Su25_base",
	"AV8B2",
	"A10",
	"D30_base",
	"ZU23_base",
	"MQ9PredatorB_US_EP1",
	"Ka137_MG_PMC",
	"Pchela1T",
	"F35B",
	"C130J_US_EP1",
	"L39_TK_EP1",
	"L39_ACR",
	"Chukar",
	"Land_Misc_Cargo1E_EP1",
	"Land_Misc_Cargo2E_EP1",
	"AW159_Lynx_BAF"
];

/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/

/**
 * List of class names of air vehicles which can lift liftables objects.
 * Liste des noms de classes des véhicules aériens pouvant héliporter des objets héliportables.
 */
R3F_LOG_CFG_heliporteurs = [
	"CH47_base_EP1",
	"Mi17_base",
	"UH1H_base",
	"UH1_Base",
	"UH60_Base",
	"Mi17_TK_EP1",
	"Mi17_medevac_Ins",
	"Ka60_GL_PMC",
	"Mi17_rockets_RU",
	"CH_47F_BAF",
	"AH1Z",
	"AH64D",
	"Ka60_Base_PMC",
	"Mi24_Base",
	"Ka52",
	"Ka52Black",
	"UH1H_TK_EP1",
	"MH60S",
	"UH60M_EP1",
	"Mi17_medevac_RU",
	"UH1Y",
	"Ka60_PMC",
	"UH1H_TK_GUE_EP1",
	"Mi17_Civilian",
	"MV22",
	"CH_47F_EP1",
	"MH6J_EP1",
	"UH60M_MEV_EP1",
	"AH6X_EP1",
	"BAF_Merlin_HC3_D",
	"Ka137_MG_PMC"
];

/**
 * List of class names of liftables objects.
 * Liste des noms de classes des objets héliportables.
 */
R3F_LOG_CFG_objets_heliportables = [

	"CH47_base_EP1",
	"AH6_Base_EP1",
	"Mi17_base",
	"Mi24_Base",
	"UH1H_base",
	"UH1_Base",
	"UH60_Base",
	"An2_Base_EP1",
	"C130J",
	"MV22",
	"F35",
	"HMMWV_Avenger",
	"HMMWV_M998A2_SOV_DES_EP1",
	"HMMWV_Base",
	"Ikarus",
	"Lada_base",
	"LandRover_Base",
	"Offroad_DSHKM_base",
	"Pickup_PK_base",
	"S1203_TK_CIV_EP1",
	"SUV_Base_EP1",
	"SkodaBase",
	"TowingTractor",
	"Tractor",
	"VWGolf",
	"BRDM2_Base",
	"BTR40_MG_base_EP1",
	"LAV25_Base",
	"BTR60_TK_EP1",
	"BTR90_Base",
	"GAZ_Vodnik_HMG",
	"LAV25_Base",
	"StrykerBase_EP1",
	"hilux1_civil_1_open",
	"hilux1_civil_3_open_EP1",
	"Motorcycle",
	"2S6M_Tunguska",
	"M113_Base",
	"MLRS",
	"T34",
	"M119",
	"T55_Base",
	"T72_Base",
	"T90",
	"AAV",
	"BMP2_Base",
	"BMP3",
	"ZSU_Base",
	"Fort_Crate_wood",
	"BAF_Merlin_HC3_D",
	"Ka60_Base_PMC",
	"ArmoredSUV_Base_PMC",
	"BAF_Jackal2_BASE_D",
	"USBasicAmmunitionBox",
	"RUBasicAmmunitionBox",
	"LocalBasicAmmunitionBox",
	"GuerillaCacheBox",
	"ReammoBox_EP1",
	"Fort_Crate_wood",
	"Land_Misc_Cargo1E_EP1",
	"Land_Misc_Cargo2E_EP1",
	"AW159_Lynx_BAF"
];


/*
 * List of class names of (ground or air) vehicles which can transport transportables objects.
 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
 * 
 * Liste des noms de classes des véhicules (terrestres ou aériens) pouvant transporter des objets transportables.
 * Le deuxième élément des tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
 */
R3F_LOG_CFG_transporteurs = [
	["CH47_base_EP1", 1600],
	["AH6_Base_EP1", 50],
	["Mi17_base", 120],
	["Mi24_Base", 100],
	["UH1H_base", 70],
	["UH1_Base", 60],
	["UH60_Base", 80],
	["An2_Base_EP1", 80],
	["C130J", 2000],
	["MV22", 160],
	["Fishing_Boat", 1000],
        ["PBX", 200],
        ["SeaFox", 200],
        ["Smallboat_1", 500],
        ["Smallboat_2", 500],
        ["Zodiac", 200],
        ["RHIB2Turret", 100],
      	["HMMWV_Avenger", 10],
	["HMMWV_M998A2_SOV_DES_EP1", 24],
	["HMMWV_Base", 36],
	["Ikarus", 1000],
	["Lada_base", 20],
	["LandRover_Base", 30],
	["Offroad_DSHKM_base", 30],
	["Pickup_PK_base", 30],
	["S1203_TK_CIV_EP1", 40],
	["SUV_Base_EP1", 30],
	["SkodaBase", 20],
	["TowingTractor", 20],
	["Tractor", 20],
	["KamazRefuel",100],
	["Kamaz_Base", 100],
	["MAZ_543_SCUD_Base_EP1", 20],
	["MtvrRefuel", 100],
	["MTVR", 100],
	["GRAD_Base", 20],
	["Ural_Base", 70],
	["Ural_ZU23_Base", 40],
	["Ural_CDF", 100],
	["Ural_INS", 100],
	["UralRefuel_Base", 20],
	["V3S_Refuel_TK_GUE_EP1", 20],
	["V3S_Civ", 100],
	["V3S_Base_EP1", 100],
	["UAZ_Base", 200],
	["VWGolf", 16],
	["Volha_TK_CIV_Base_EP1", 16],
	["BRDM2_Base", 30],
	["BTR40_MG_base_EP1", 30],
	["BTR60_TK_EP1", 30],
	["GAZ_Vodnik_HMG", 50],
	["StrykerBase_EP1", 50],
	["hilux1_civil_1_open", 24],
	["hilux1_civil_3_open_EP1", 24],
	["Motorcycle", 10],
	["M113_Base", 24],
	["ZSU_Base", 20],
	["Ship", 500],
	["Fort_Crate_wood", 40],
	["BAF_Merlin_HC3_D",150],
	["Ka60_Base_PMC", 80],
	["ArmoredSUV_Base_PMC",24],
	["BAF_Jackal2_BASE_D", 30],
        ["Land_Misc_Cargo1E_EP1", 1000],
	["Land_Misc_Cargo2E_EP1", 2000]
];

/**
 * List of class names of transportables objects.
 * The second element of the arrays is the cost capacity (in relation with the capacity of the vehicles).
 * 
 * Liste des noms de classes des objets transportables.
 * Le deuxième élément des tableaux est le coût de capacité (en relation avec la capacité des véhicules).
 */
 
R3F_LOG_CFG_objets_transportables =  [
["GraveCross2_EP1",5],
["Land_Carpet_EP1",5],
["Land_Water_pipe_EP1",5],
["Land_ladder_half_EP1",5],
["Land_ladderEP1",5],
["Bleacher_EP1",10],
["Land_Hlidac_Budka_EP1",50],
["Land_Barrack2_EP1",50],
["WaterBasin_conc_EP1",100],
["HeliHRescue",5],
["HeliHCivil",5],
["PARACHUTE_TARGET",5],
["Land_Ind_Shed_01_main",20],
["Land_Farm_WTower",20],
["Land_A_Castle_Bergfrit",100],
["Land_Hangar_2",100],
["PowGen_Big_EP1",20],
["Mass_grave",10],
["Hanged",5],
["Hanged_MD",5],
["Land_CamoNetB_EAST",10],
["TK_WarfareBFieldhHospital_EP1",50],
["US_WarfareBFieldhHospital_EP1",50],
	["Pchela1T", 15],
	
	["FoldChair_with_Cargo", 1],
	["Chukar", 15],
	["MMT_base", 1],
	["Old_bike_base_EP1", 1],
	["M2StaticMG", 4],
	["Land_HBarrier1", 4],
	["Land_HBarrier3", 4],
	["M1030", 5],
	["Old_moto_base", 5],
	["TT650_Base", 5],
	["Igla_AA_pod_East", 7],
	["Stinger_Pod_base", 7],
	["Metis", 4],
	["SPG9_base", 4],
	["TOW_TriPod", 5],
	["TOW_TriPod_Base", 5],
	["TOW_TriPod_US_EP1", 5],
	["AGS_base", 4],
	["MK19_TriPod", 4],
	["DSHKM_base", 4],
	["KORD_Base", 5],
	["M2StaticMG_base", 4],
	["WarfareBMGNest_M240_base", 10],
	["WarfareBMGNest_PK_Base", 10],
	["2b14_82mm", 4],
	["M252", 4],
	["Warfare2b14_82mm_Base", 4],
	["StaticSEARCHLight", 4],
	["FlagCarrierSmall", 1],
	["Fort_Crate_wood", 2],
	["Fort_RazorWire", 2],
	["Base_WarfareBBarrier10xTall", 10],
	["Base_WarfareBBarrier10x", 7],
	["Base_WarfareBBarrier5x", 5],
	["Fort_EnvelopeBig", 1],
	["Fort_EnvelopeSmall", 1],
	["Land_Fire_barrel", 1],
	["Land_GuardShed", 3],
	["Land_fort_rampart_EP1", 5],
	["Land_fort_bagfence_corner", 2],
	["Land_fort_bagfence_long", 2],
	["Land_fort_bagfence_round", 3],
	["Land_fortified_nest_small_EP1", 6],
	["Land_fortified_nest_small", 6],
	["Land_tent_east", 6],
	["Land_BagFenceCorner", 2],
	["Land_HBarrier_large", 3],
	["Land_Toilet", 3],
	["RoadBarrier_light", 2],
	["ACamp", 3],
	["Camp", 5],
	["CampEast", 6],
	["MASH", 5],
	["FlagCarrier", 1],
	["FlagCarrierChecked", 1],
	["Hedgehog", 3],
	["Hedgehog_EP1", 3],
	["AmmoCrate_NoInteractive_Base_EP1", 5],
	["RUVehicleBox", 12],
	["TKVehicleBox_EP1", 12],
	["USVehicleBox_EP1", 12],
	["USVehicleBox", 12],
	["USBasicAmmunitionBox", 5],
	["RUBasicAmmunitionBox", 5],
	["LocalBasicAmmunitionBox", 5],
	["GuerillaCacheBox", 5],
	["ReammoBox_EP1", 5],
	["Desk", 1],
	["Land_Bench_EP1", 1],
	["Land_sunshade_EP1", 1],
	["WoodChair", 1],
	["Land_radar_EP1", 8],
	["Sign_Danger", 1],
	["Sign_Checkpoint_US_EP1", 1],
	["Land_coneLight", 1],
	["SearchLight", 2],
	["Land_KBud", 3],
	["Land_kulna", 5],
	["Land_Shed_wooden", 5],
	["FoldChair", 1],
	["FoldTable", 1],
	["BarrelBase", 2],
	["Notice_board", 1],
	["SmallTable", 1],
	["Notebook", 1],
	["Land_Chair_EP1", 1],
	["Land_Misc_Scaffolding", 5],
	["Suitcase",1],
	["Fuel_can",1],
	["Land_Barrel_water",2],
	["Land_Teapot_EP1",1],
	["Land_Sack_EP1",1],
	["Land_Bag_EP1",1],
	["Land_Campfire_burning",1],
	["Land_Fire_barrel_burning",1],
	["Land_fort_bagfence_corner",2],
	["Land_HBarrier5",3],
	["Land_BagFenceLong",2],
	["Land_fortified_nest_big_EP1", 15],
	["Fort_EnvelopeBig_EP1",3],
	["Fort_EnvelopeSmall_EP1",2],
	["Fort_StoneWall_EP1",2],
	["Land_Fort_Watchtower_EP1",8],
	["Land_Misc_Rubble_EP1",2],
	["Land_stand_small_EP1",1],
	["Fort_RazorWire",1],
	["Land_HBarrier_large",7],
	["Land_HBarrier5",3],
	["Fort_Barricade",4],
	["Land_fort_artillery_nest",10],
	["Land_fort_rampart",6],
	["Land_fortified_nest_small",3],
	["Land_fort_bagfence_round", 2],
	["Base_WarfareBBarrier10xTall", 10],
	["Base_WarfareBBarrier10x", 8],
	["Land_Misc_deerstand", 3],
	["Barrack2", 15],
	["Land_Fort_Watchtower", 8],
	["Land_Dirthump01", 10],
	["Land_CncBlock_Stripes", 2],
	["Land_CncBlock", 2],
	["Land_fortified_nest_big", 15],
	["Land_RedWhiteBarrier", 2],
	["Land_ladder_half", 3],
	["Land_ladder", 5],
	["Land_WoodenRamp", 2],
	["Land_prebehlavka", 4],
	["Land_prolejzacka", 5],
	["Land_ConcreteRamp", 15],
	["Land_ConcreteBlock", 20],
	["RampConcrete", 10],
	["Land_Misc_ConcPipeline_EP1", 5],
	["Concrete_Wall_EP1", 5],
	["Paleta1", 2],
	["Obstacle_saddle", 2],
	["Land_Climbing_Obstacle", 3],
	["Fort_StoneWall_EP1", 5],
	["Land_CamoNet_NATO", 3],
	["WarfareBCamp", 15],
	["WarfareBDepot", 100],
	["Land_A_Castle_Stairs_A",15],
	["Land_leseni2x", 8],
	["Land_leseni4x", 15],
	["Wall_L_2m5_EP1", 5],
	["Land_Misc_Cargo1Eo_EP1", 8],
	["Land_Misc_Cargo1E_EP1", 25],
	["Land_Misc_Cargo2E_EP1", 30],
	["Hhedgehog_concrete", 10],
	["Hhedgehog_concreteBig", 10],	
	["Land_A_Castle_Stairs_A", 8],
	["Land_obihacka", 4],
	["Land_obstacle_run_duck", 7],
	["Land_Climbing_Obstacle",3],
	["TK_GUE_WarfareBFieldhHospital_EP1", 10],
	["TargetFakeTank_EP1", 5],
	["SignM_FARP_Winchester_EP1", 1],
	["Sign_Checkpoint_TK_EP1", 1],
	["Land_radar", 10],
	["Land_covering_hut_EP1", 3],
	["Land_covering_hut_big_EP1", 5],
	["Land_Reservoir_EP1", 3],
	["KORD_TK_EP1", 5],
	["M2HD_mini_TriPod", 5],
	["BAF_GPMG_Minitripod_D", 5],
	["KORD_high_TK_EP1", 5],
	["BAF_L2A1_Minitripod_D", 5],
	["BAF_GMG_Tripod_D", 5],
	["SPG9_TK_GUE_EP1", 5],
	["AGS_TK_EP1", 5],
	["BAF_L2A1_Tripod_D", 5],
	["DSHKM_TK_GUE_EP1", 5],
	["DSHkM_Mini_TriPod_TK_EP1", 5],
	["Fort_Nest_M240", 8],
	["Land_vez", 8],
	["MASH_EP1", 5],
	["HeliH", 1],
	["Garbage_container", 3],
	["TK_WarfareBFieldhHospital_EP1", 15],
	["Misc_concrete_High", 6],
	["Land_Ind_BoardsPack1", 6],
	["Land_Ind_BoardsPack2", 6],
	["Land_Ind_Timbers", 8],
	["Land_Misc_Coil_EP1", 4],
	["Land_Table_EP1", 6],
	["CampEast_EP1", 8],
	["WarfareBMGNest_PK_TK_EP1", 8],
	["WarfareBMGNest_M240_US_EP1", 8],
	["US_WarfareBFieldhHospital_EP1", 18],
	["PowerGenerator", 10],
	["Land_Antenna", 15],
	["BAF_L2A1_ACOG_base", 4],
	["FlagCarrierGermany_EP1", 1],
	["FlagCarrierRU", 1],
	["FlagCarrierUSA", 1],
	["FlagCarrierBLUFOR_EP1", 1],
	["FlagCarrierOPFOR_EP1", 1],
	["FlagCarrierINDFOR_EP1", 1],
	["FlagCarrierRedCross_EP1", 1],
	["FlagCarrierNATO_EP1", 1],
	["SearchLight_TK_EP1", 1],
	["ZU23_Ins", 7],
	["GMG_TriPod", 4],
	["ZU23_base", 7],
	["Land_runway_edgelight", 1],
	["Ka137_Base_PMC", 15],
	["BAF_L2A1_ACOG_base", 4],
	["GMG_TriPod", 4],
	["Land_Ind_SawMillPen", 20],
	["Land_Misc_Cargo2E", 8],
	["Land_Misc_Cargo1D", 16],
	["Land_ladder", 4],
	["Land_ladder", 2],
        ["Land_fortified_nest_big_EP1",15]
];

/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/

/**
 * List of class names of objects moveables by player.
 * Liste des noms de classes des objets transportables par le joueur.
 */

R3F_LOG_CFG_objets_deplacables = [
"HeliHCivil",
"Fort_RazorWire",
"GraveCross2",
"Hanged",
"Land_A_Castle_Bergfrit",
"Land_A_Castle_Donjon",
"Land_A_Castle_Gate",
"Land_A_Castle_Wall1_20",
"Land_A_Castle_Wall1_20_Turn",
"Land_A_Castle_Wall1_Corner",
"Land_A_Castle_Wall1_Corner_2",
"Land_A_Castle_Wall1_End",
"Land_A_Castle_Wall1_End_2",
"Land_A_Castle_Wall2_30",
"Land_A_Castle_Wall2_End",
"Land_A_Castle_Wall2_End_2",
"USMC_WarfareBAircraftFactory",
"TK_GUE_WarfareBUAVterminal_EP1",
"GraveCross2_EP1",
"Land_Carpet_EP1",
"Land_Water_pipe_EP1",
"Land_ladder_half_EP1",
"Land_ladderEP1",
"Bleacher_EP1",
"Land_Hlidac_Budka_EP1",
"WaterBasin_conc_EP1",
"HeliHRescue",
"HeliHCivil",
"PARACHUTE_TARGET",
"Land_Ind_Shed_01_main",
"Land_Farm_WTower",
"Land_A_Castle_Bergfrit",
"Land_Hangar_2",
"PowGen_Big_EP1",
"Mass_grave",
"Hanged",
"Hanged_MD",
"Land_Hangar_2",
"Land_A_Castle_Bergfrit",
"GUE_WarfareBUAVterminal",
"Land_transport_cart_EP1",
"Land_transport_crates_EP1",
"Haystack_small",
"Land_Ind_IlluminantTower",
"Land_Misc_Cargo1Ao",
"Land_CamoNetB_EAST",
"TK_WarfareBFieldhHospital_EP1",
"US_WarfareBFieldhHospital_EP1",
	"Land_covering_hut_big_EP1",
	"ZU23_Ins",
	"Fort_Nest_M240",
	"BAF_GMG_Tripod_D",
	"SPG9_TK_GUE_EP1",
	"M2HD_mini_TriPod",
	"AGS_TK_EP1",
	"M2StaticMG",
	"TOW_TriPod_US_EP1",
	"BAF_GPMG_Minitripod_D",
	"BAF_L2A1_Tripod_D",
	"BAF_L2A1_Minitripod_D",
	"MK19_TriPod",
	"KORD_TK_EP1",
	"KORD_high_TK_EP1",
	"DSHKM_TK_GUE_EP1",
	"DSHkM_Mini_TriPod_TK_EP1",
	"SearchLight_TK_EP1",
	"WarfareBMGNest_PK_TK_EP1",
	"Land_KBud",
	"Land_covering_hut_EP1",
	"Land_fort_artillery_nest_EP1",
	"Land_Misc_Cargo1Eo_EP1",
	"Land_Misc_Coil_EP1",
	"Land_sunshade_EP1",
	"Land_Ind_Timbers",
	"Land_Table_EP1",
	"Land_Bench_EP1",
	"Land_Ind_BoardsPack1",
	"WoodChair",
	"Hedgehog_EP1",
	"US_WarfareBFieldhHospital_EP1",
	"Fort_Barricade_EP1",
	"Land_HBarrier3",
	"Land_Barrack2_EP1",
	"Misc_concrete_High",
	"Land_Ind_BoardsPack2",
	"CampEast_EP1",
	"Land_HBarrier1",
	"Land_fort_rampart_EP1",
	"Land_fortified_nest_big_EP1",
	"Land_fortified_nest_small_EP1",
	"Land_Shed_wooden",
	"FlagCarrierGermany_EP1",
	"FlagCarrierRU",
	"FlagCarrierUSA",
	"FlagCarrierBLUFOR_EP1",
	"FlagCarrierOPFOR_EP1",
	"FlagCarrierINDFOR_EP1",
	"FlagCarrierRedCross_EP1",
	"FlagCarrierNATO_EP1",
	"TK_WarfareBFieldhHospital_EP1",
	"ZavoraAnim",
	"Land_Misc_Cargo2E_EP1",
	"Land_Misc_Cargo1E_EP1",
	"Land_kulna",
    "Hhedgehog_concrete",
    "Hhedgehog_concreteBig",
    "Sign_Checkpoint_US_EP1",
    "Sign_Checkpoint_TK_EP1",
    "Sign_Danger",
    "Land_CamoNet_NATO",
	"FoldChair_with_Cargo",
	"StaticWeapon",
	"FlagCarrierSmall",
	"Fort_Crate_wood",
	"Fort_RazorWire",
	"Gunrack1",
	"Base_WarfareBBarrier5x",
	"Fort_EnvelopeBig",
	"Fort_EnvelopeSmall",
	"Land_A_tent",
	"Land_Antenna",
	"Land_Fire_barrel",
	"Land_GuardShed",
	"Land_fort_bagfence_corner",
	"Land_fort_bagfence_long",
	"Land_fort_bagfence_round",
	"Land_fortified_nest_small",
	"Land_tent_east",
	"Land_HBarrier_large",
	"Land_Toilet",
	"RoadBarrier_light",
	"WarfareBunkerSign",
	"ACamp",
	"Camp",
	"CampEast",
	"MASH",
	"FlagCarrier",
	"FlagCarrierChecked",
	"Hedgehog",
	"AmmoCrate_NoInteractive_Base_EP1",
	"ReammoBox",
	"TargetE",
	"TargetEpopup",
	"TargetPopUpTarget",
	"Desk",
	"FoldChair",
	"FoldTable",
	"Land_Barrel_empty",
	"Land_Barrel_sand",
	"Land_Barrel_water",
	"Land_arrows_yellow_L",
	"Land_arrows_yellow_R",
	"Land_coneLight",
	"BarrelBase",
	"Fuel_can",
	"SmallTable",
	"Notebook",
	"Radio",
	"SmallTV",
	"Land_Chair_EP1",
	"Suitcase",
	"Land_Misc_deerstand",
	"Land_Fort_Watchtower",
	"Land_CncBlock_Stripes",
	"Land_CncBlock",
	"Land_Dirthump01",
	"Barrack2",
	"Land_radar_EP1",
	"Land_vez",
	"Land_fortified_nest_big",
	"Base_WarfareBBarrier10x",
	"Base_WarfareBBarrier10xTall",
	"Land_Teapot_EP1",
	"Land_Sack_EP1",
	"Land_Bag_EP1",
	"Land_Campfire_burning",
	"Land_Fire_barrel_burning",
	"Land_HBarrier5",
	"Land_BagFenceLong",
	"Fort_EnvelopeBig_EP1",
	"Fort_EnvelopeSmall_EP1",
	"Fort_StoneWall_EP1",
	"Land_Fort_Watchtower_EP1",
	"Land_Misc_IronPipes_EP1",
	"Land_Misc_Rubble_EP1",
	"Land_stand_small_EP1",
	"Fort_Barricade",
	"Land_fort_artillery_nest",
	"Land_fort_rampart",
	"Land_RedWhiteBarrier",
	"Land_ladder_half",
	"Land_ConcreteRamp",
	"Land_WoodenRamp",
	"Land_prebehlavka",
	"Land_prolejzacka",
	"RampConcrete",
    "Land_Misc_Scaffolding",
	"Land_A_Castle_Stairs_A",
	"WaterBasin_conc_EP1",
	"Land_Misc_ConcPipeline_EP1",
	"Land_ConcreteBlock",
	"Paleta1",
	"Misc_cargo_cont_tiny",
	"Concrete_Wall_EP1",
	"PowerGenerator",
	"WarfareBCamp",
	"WarfareBDepot",
	"BAF_L2A1_ACOG_base",
	"GMG_TriPod",
	"Land_runway_edgelight",
	"Obstacle_saddle",
	"Land_Climbing_Obstacle",
	"Ka137_Base_PMC",
	"Land_leseni2x",
	"Land_leseni4x",
	"Wall_L_2m5_EP1",
	"M1130_HQ_unfolded_Base_EP1",
	
	"Motorcycle",
	"Land_Ind_SawMillPen",
	"Land_Misc_Cargo2E",
	"Land_Misc_Cargo1D",
	"Land_ladder",
	"Land_ladder",
       "Land_fortified_nest_big_EP1"
];
